import Sidebar from '@/components/Sidebar'
import './globals.css'
import { Nunito } from 'next/font/google'

const nunito = Nunito({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang='en'>
      <body className={`grid grid-cols-[1fr_3fr] h-full ${nunito.className}`}>
        <Sidebar />
        <main>{children}</main>
      </body>
    </html>
  )
}
